name: BuildAndTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Build Packages
      run: |
        ./lambdas/build/package.sh
    - name: Run Unit Tests
      run: |        
        ./lambdas/build/unittest.sh
    - name: Show Code Coverage Report
      run: |
        ./lambdas/build/code_coverage_report.sh
    - name: Code Profiling
      run: |
        ./lambdas/build/code_profiling_report.sh
    - name: Analysing the code with pylint
      run: |
        pylint --exit-zero --recursive yes ./lambdas/applications/* ./lambdas/layers/*
